"""Add price field to Course model

Revision ID: 4a7c7ed07ae2
Revises: 4e396f3d951d
Create Date: 2025-03-26 21:21:53.885552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7c7ed07ae2'
down_revision = '4e396f3d951d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
